Update Inconceivable-API.yml

diff --git a/.github/workflows/Inconceivable-API.yml b/.github/workflows/Inconceivable-API.yml
--- a/.github/workflows/Inconceivable-API.yml
+++ b/.github/workflows/Inconceivable-API.yml
@@ -1,40 +1,87 @@
-name: Build and deploy .NET Core app to Windows WebApp Inconceivable-API
+# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
+# More GitHub Actions for Azure: https://github.com/Azure/actions
+
+name: Build and deploy ASP.Net Core app to Azure Web App - WordleApiClass
+
 on:
   push:
     branches:
-    - Assignment3
-env:
-  AZURE_WEBAPP_NAME: Inconceivable-API
-  AZURE_WEBAPP_PACKAGE_PATH: Wordle.Api/publish
-  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.Inconceivable_API_7cec }}
-  CONFIGURATION: Release
-  DOTNET_CORE_VERSION: 6.0.x
-  WORKING_DIRECTORY: Wordle.Api
+      - main
+      - "Assignment*"
+    paths:
+      - 'Wordle.api/**'
+  workflow_dispatch:
+
 jobs:
-  build-and-deploy:
+  build:
     runs-on: windows-latest
+
     steps:
-    - uses: actions/checkout@v2
-    - name: Setup .NET Core
-      uses: actions/setup-dotnet@v1
-      with:
-        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
-    - name: Restore
-      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
-    - name: Build
-      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
-    - name: Test
-      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
-    - name: Publish
-      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
-    - name: Deploy to Azure WebApp
-      uses: azure/webapps-deploy@v2
-      with:
-        app-name: ${{ env.AZURE_WEBAPP_NAME }}
-        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
-        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
-    - name: Publish Artifacts
-      uses: actions/upload-artifact@v1.0.0
-      with:
-        name: webapp
-        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
+      - uses: actions/checkout@v2
+
+      - name: Set up .NET Core
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '6.0.x'
+          include-prerelease: true
+                
+      - name: Set up dependency caching for faster builds
+        uses: actions/cache@v3
+        with:
+          path: ~/.nuget/packages
+          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-nuget-
+
+      - name: Build with dotnet
+        run: dotnet build --configuration Release
+        
+      - name: Test with dotnet
+        run: dotnet test --logger "trx;LogFileName=test-results.trx" --no-restore
+        
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: .NET Tests            # Name of the check run which will be created
+          path: '**/test-results.trx'    # Path to test results
+          reporter: dotnet-trx        # Format of test results
+
+      - name: Upload Test TRX file
+        uses: actions/upload-artifact@v2  # upload test results
+        continue-on-error: true       # if there are no test results, this should still pass.
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: dotnet-trx
+          path: '**/test-results.trx'
+
+      - name: dotnet publish
+        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
+
+      - name: Upload artifact for deployment job
+        uses: actions/upload-artifact@v2
+        with:
+          name: .net-app
+          path: ${{env.DOTNET_ROOT}}/myapp
+
+  deploy:
+    runs-on: windows-latest
+    needs: build
+    environment:
+      name: 'Production'
+      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
+
+    steps:
+      - name: Download artifact from build job
+        uses: actions/download-artifact@v2
+        with:
+          name: .net-app
+
+      - name: Deploy to Azure Web App
+        id: deploy-to-webapp
+        uses: azure/webapps-deploy@v2
+        with:
+          app-name: 'Inconceivable-API'
+          slot-name: 'Production'
+          publish-profile: ${{ secrets.API_AZUREAPPSERVICE_PUBLISHPROFILE }}
+          package: .
